// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: string;
};

export type RegisterDto = {
  name: string;
  surname: string;
  email: string;
  password: string;
};

export type AuthResponseDto = {
  accessToken: string;
  refreshToken: string;
  user: {
    id: string;
    name: string;
    surname: string;
    email: string;
  };
};

export type ErrorResponseDto = {
  statusCode: number;
  message: string;
  error: string;
};

export type LoginDto = {
  email: string;
  password: string;
};

export type RefreshTokenDto = {
  refreshToken: string;
};

export type LogoutResponseDto = {
  success: boolean;
};

export type ValidateTokenDto = {
  authToken: string;
};

export type ValidateTokenResponseDto = {
  isValid: boolean;
  user: {
    sub: string;
    email: string;
    type: 'access' | 'refresh';
  };
};

export type CreateTransactionDto = {
  type: 'income' | 'expense';
  amount: number;
  category:
    | 'salary'
    | 'rent'
    | 'utilities'
    | 'leasing'
    | 'office'
    | 'services'
    | 'maintenance'
    | 'materials'
    | 'equipment'
    | 'transport'
    | 'marketing'
    | 'software'
    | 'other'
    | 'sales'
    | 'consulting';
  description?: string;
  date: string;
};

export type TransactionResponseDto = {
  id: string;
  userId: string;
  type: 'income' | 'expense';
  amount: number;
  category:
    | 'salary'
    | 'rent'
    | 'utilities'
    | 'leasing'
    | 'office'
    | 'services'
    | 'maintenance'
    | 'materials'
    | 'equipment'
    | 'transport'
    | 'marketing'
    | 'software'
    | 'other'
    | 'sales'
    | 'consulting';
  description?: string;
  date: string;
};

export type FinancialReportResponseDto = {
  userId: string;
  period: {
    type: 'monthly' | 'quarterly' | 'annual';
    startDate: string;
    endDate: string;
  };
  generatedAt: string;
  revenue: {
    grossRevenue: number;
    netRevenue: number;
    vatCollected: number;
  };
  expenses: {
    grossExpenses: number;
    netExpenses: number;
    vatDeductible: number;
    payrollExpenses: {
      grossSalaries: number;
      netSalaries: number;
      pensionFund: number;
      medicalFund: number;
      socialInsuranceFund: number;
      totalPayrollTaxes: number;
      totalPayrollCost: number;
    };
    socialContributionExpenses: {
      pensionFund: number;
      medicalFund: number;
      socialInsuranceFund: number;
      otherContributions: number;
      totalSocialContributions: number;
    };
    administrativeExpenses: {
      rent: number;
      utilities: number;
      leasing: number;
      office: number;
      services: number;
      maintenance: number;
      totalAdministrativeExpenses: number;
    };
    taxExpenses: {
      vatToPay: number;
      corporateIncomeTax: number;
      otherTaxes: number;
      totalTaxExpense: number;
    };
    operationalExpenses: {
      materials: number;
      equipment: number;
      transport: number;
      marketing: number;
      software: number;
      totalOperationalExpenses: number;
    };
    otherExpenses: {
      uncategorized: number;
      totalOtherExpenses: number;
    };
  };
  vat: {
    vatCollectedFromRevenue: number;
    vatDeductibleFromExpenses: number;
    vatToPay: number;
  };
  corporateResult: {
    netRevenue: number;
    netExpenses: number;
    payrollCost: number;
    operatingProfit: number;
  };
  finalResult: {
    profitBeforeTax: number;
    incomeTax: number;
    profitAfterTax: number;
  };
};

export type PaginatedTransactionsResponseDto = {
  items: Array<{
    id: string;
    userId: string;
    type: 'income' | 'expense';
    amount: number;
    category:
      | 'salary'
      | 'rent'
      | 'utilities'
      | 'leasing'
      | 'office'
      | 'services'
      | 'maintenance'
      | 'materials'
      | 'equipment'
      | 'transport'
      | 'marketing'
      | 'software'
      | 'other'
      | 'sales'
      | 'consulting';
    description?: string;
    date: string;
  }>;
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
};

export type DeleteTransactionsDto = {
  transactionIds: Array<string>;
};

export type DeleteTransactionsResponseDto = {
  deletedCount: number;
};

export type AuthControllerRegisterData = {
  /**
   * Registration data required to create a new account.
   */
  body: RegisterDto;
  path?: never;
  query?: never;
  url: '/api/auth/register';
};

export type AuthControllerRegisterErrors = {
  /**
   * Request body failed validation.
   */
  400: ErrorResponseDto;
  /**
   * A user with the same email already exists.
   */
  409: ErrorResponseDto;
};

export type AuthControllerRegisterError =
  AuthControllerRegisterErrors[keyof AuthControllerRegisterErrors];

export type AuthControllerRegisterResponses = {
  /**
   * User registered successfully.
   */
  201: AuthResponseDto;
};

export type AuthControllerRegisterResponse =
  AuthControllerRegisterResponses[keyof AuthControllerRegisterResponses];

export type AuthControllerLoginData = {
  /**
   * Login credentials.
   */
  body: LoginDto;
  path?: never;
  query?: never;
  url: '/api/auth/login';
};

export type AuthControllerLoginErrors = {
  /**
   * Request body failed validation.
   */
  400: ErrorResponseDto;
  /**
   * Email or password is invalid.
   */
  401: ErrorResponseDto;
};

export type AuthControllerLoginError =
  AuthControllerLoginErrors[keyof AuthControllerLoginErrors];

export type AuthControllerLoginResponses = {
  /**
   * User authenticated successfully.
   */
  200: AuthResponseDto;
};

export type AuthControllerLoginResponse =
  AuthControllerLoginResponses[keyof AuthControllerLoginResponses];

export type AuthControllerLogoutData = {
  /**
   * Refresh token payload used to identify the session.
   */
  body: RefreshTokenDto;
  path?: never;
  query?: never;
  url: '/api/auth/logout';
};

export type AuthControllerLogoutErrors = {
  /**
   * Request body failed validation.
   */
  400: ErrorResponseDto;
  /**
   * Refresh token is invalid or expired.
   */
  401: ErrorResponseDto;
};

export type AuthControllerLogoutError =
  AuthControllerLogoutErrors[keyof AuthControllerLogoutErrors];

export type AuthControllerLogoutResponses = {
  /**
   * User logged out successfully.
   */
  200: LogoutResponseDto;
};

export type AuthControllerLogoutResponse =
  AuthControllerLogoutResponses[keyof AuthControllerLogoutResponses];

export type AuthControllerRefreshTokenData = {
  /**
   * Refresh token payload.
   */
  body: RefreshTokenDto;
  path?: never;
  query?: never;
  url: '/api/auth/refresh-token';
};

export type AuthControllerRefreshTokenErrors = {
  /**
   * Request body failed validation.
   */
  400: ErrorResponseDto;
  /**
   * Refresh token is invalid or expired.
   */
  401: ErrorResponseDto;
};

export type AuthControllerRefreshTokenError =
  AuthControllerRefreshTokenErrors[keyof AuthControllerRefreshTokenErrors];

export type AuthControllerRefreshTokenResponses = {
  /**
   * Token pair refreshed successfully.
   */
  200: AuthResponseDto;
};

export type AuthControllerRefreshTokenResponse =
  AuthControllerRefreshTokenResponses[keyof AuthControllerRefreshTokenResponses];

export type AuthControllerValidateTokenData = {
  /**
   * Token validation payload.
   */
  body: ValidateTokenDto;
  path?: never;
  query?: never;
  url: '/api/auth/validate-token';
};

export type AuthControllerValidateTokenErrors = {
  /**
   * Request body failed validation.
   */
  400: ErrorResponseDto;
  /**
   * Token is invalid or expired.
   */
  401: ErrorResponseDto;
};

export type AuthControllerValidateTokenError =
  AuthControllerValidateTokenErrors[keyof AuthControllerValidateTokenErrors];

export type AuthControllerValidateTokenResponses = {
  /**
   * Token is valid.
   */
  200: ValidateTokenResponseDto;
};

export type AuthControllerValidateTokenResponse =
  AuthControllerValidateTokenResponses[keyof AuthControllerValidateTokenResponses];

export type FinancialControllerDeleteTransactionsData = {
  /**
   * Ids selected by the user for deletion.
   */
  body: DeleteTransactionsDto;
  path?: never;
  query?: never;
  url: '/api/transactions';
};

export type FinancialControllerDeleteTransactionsErrors = {
  /**
   * Authorization header is missing, body is invalid or no transaction ids were provided.
   */
  400: ErrorResponseDto;
  /**
   * Bearer token is invalid or expired.
   */
  401: ErrorResponseDto;
};

export type FinancialControllerDeleteTransactionsError =
  FinancialControllerDeleteTransactionsErrors[keyof FinancialControllerDeleteTransactionsErrors];

export type FinancialControllerDeleteTransactionsResponses = {
  /**
   * Transactions deleted successfully.
   */
  200: DeleteTransactionsResponseDto;
};

export type FinancialControllerDeleteTransactionsResponse =
  FinancialControllerDeleteTransactionsResponses[keyof FinancialControllerDeleteTransactionsResponses];

export type FinancialControllerGetTransactionsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page number used for transaction pagination.
     */
    page?: number;
    /**
     * Number of transactions returned per page.
     */
    limit?: number;
  };
  url: '/api/transactions';
};

export type FinancialControllerGetTransactionsErrors = {
  /**
   * Authorization header is missing or malformed.
   */
  400: ErrorResponseDto;
  /**
   * Bearer token is invalid or expired.
   */
  401: ErrorResponseDto;
};

export type FinancialControllerGetTransactionsError =
  FinancialControllerGetTransactionsErrors[keyof FinancialControllerGetTransactionsErrors];

export type FinancialControllerGetTransactionsResponses = {
  /**
   * Transactions loaded successfully.
   */
  200: PaginatedTransactionsResponseDto;
};

export type FinancialControllerGetTransactionsResponse =
  FinancialControllerGetTransactionsResponses[keyof FinancialControllerGetTransactionsResponses];

export type FinancialControllerCreateTransactionData = {
  /**
   * Transaction data to be saved in the financial service.
   */
  body: CreateTransactionDto;
  path?: never;
  query?: never;
  url: '/api/transactions';
};

export type FinancialControllerCreateTransactionErrors = {
  /**
   * Invalid authorization header, invalid body or incompatible type/category pair.
   */
  400: ErrorResponseDto;
  /**
   * Bearer token is invalid or expired.
   */
  401: ErrorResponseDto;
};

export type FinancialControllerCreateTransactionError =
  FinancialControllerCreateTransactionErrors[keyof FinancialControllerCreateTransactionErrors];

export type FinancialControllerCreateTransactionResponses = {
  /**
   * Transaction created successfully.
   */
  201: TransactionResponseDto;
};

export type FinancialControllerCreateTransactionResponse =
  FinancialControllerCreateTransactionResponses[keyof FinancialControllerCreateTransactionResponses];

export type FinancialControllerGetFinancialReportData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Requested report aggregation period.
     */
    period: 'monthly' | 'quarterly' | 'annual';
    /**
     * Inclusive report start date in ISO format.
     */
    startDate: string;
    /**
     * Inclusive report end date in ISO format.
     */
    endDate: string;
  };
  url: '/api/transactions/report';
};

export type FinancialControllerGetFinancialReportErrors = {
  /**
   * Invalid authorization header, invalid query or invalid date range.
   */
  400: ErrorResponseDto;
  /**
   * Bearer token is invalid or expired.
   */
  401: ErrorResponseDto;
};

export type FinancialControllerGetFinancialReportError =
  FinancialControllerGetFinancialReportErrors[keyof FinancialControllerGetFinancialReportErrors];

export type FinancialControllerGetFinancialReportResponses = {
  /**
   * Financial report generated successfully.
   */
  200: FinancialReportResponseDto;
};

export type FinancialControllerGetFinancialReportResponse =
  FinancialControllerGetFinancialReportResponses[keyof FinancialControllerGetFinancialReportResponses];

export type FinancialControllerGetFinancialReportPdfData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Requested report aggregation period.
     */
    period: 'monthly' | 'quarterly' | 'annual';
    /**
     * Inclusive report start date in ISO format.
     */
    startDate: string;
    /**
     * Inclusive report end date in ISO format.
     */
    endDate: string;
  };
  url: '/api/transactions/report/pdf';
};

export type FinancialControllerGetFinancialReportPdfErrors = {
  /**
   * Invalid authorization header, invalid query or invalid date range.
   */
  400: ErrorResponseDto;
  /**
   * Bearer token is invalid or expired.
   */
  401: ErrorResponseDto;
};

export type FinancialControllerGetFinancialReportPdfError =
  FinancialControllerGetFinancialReportPdfErrors[keyof FinancialControllerGetFinancialReportPdfErrors];

export type FinancialControllerGetFinancialReportPdfResponses = {
  /**
   * PDF report generated successfully.
   */
  200: Blob | File;
};

export type FinancialControllerGetFinancialReportPdfResponse =
  FinancialControllerGetFinancialReportPdfResponses[keyof FinancialControllerGetFinancialReportPdfResponses];
