// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zRegisterDto = z.object({
  name: z.string().min(1),
  surname: z.string().min(1),
  email: z
    .email()
    .regex(
      /^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/,
    ),
  password: z
    .string()
    .min(8)
    .regex(/^(?=.*[A-Za-z])(?=.*\d).+$/),
});

export const zAuthResponseDto = z.object({
  accessToken: z.string().min(1),
  refreshToken: z.string().min(1),
  user: z.object({
    id: z.string(),
    name: z.string().min(1),
    surname: z.string().min(1),
    email: z
      .email()
      .regex(
        /^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/,
      ),
  }),
});

export const zErrorResponseDto = z.object({
  statusCode: z.number(),
  message: z.string(),
  error: z.string(),
});

export const zLoginDto = z.object({
  email: z
    .email()
    .regex(
      /^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/,
    ),
  password: z.string().min(1),
});

export const zRefreshTokenDto = z.object({
  refreshToken: z.string().min(1),
});

export const zLogoutResponseDto = z.object({
  success: z.boolean(),
});

export const zValidateTokenDto = z.object({
  authToken: z.string().min(1),
});

export const zValidateTokenResponseDto = z.object({
  isValid: z.boolean(),
  user: z.object({
    sub: z.string().min(1),
    email: z
      .email()
      .regex(
        /^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/,
      ),
    type: z.enum(['access', 'refresh']),
  }),
});

export const zCreateTransactionDto = z.object({
  type: z.enum(['income', 'expense']),
  amount: z.number().gt(0),
  category: z.enum([
    'salary',
    'rent',
    'utilities',
    'leasing',
    'office',
    'services',
    'maintenance',
    'materials',
    'equipment',
    'transport',
    'marketing',
    'software',
    'other',
    'sales',
    'consulting',
  ]),
  description: z.string().optional(),
  date: z.iso
    .date()
    .regex(
      /^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$/,
    ),
});

export const zTransactionResponseDto = z.object({
  id: z.string().min(1),
  userId: z.string().min(1),
  type: z.enum(['income', 'expense']),
  amount: z.number().gt(0),
  category: z.enum([
    'salary',
    'rent',
    'utilities',
    'leasing',
    'office',
    'services',
    'maintenance',
    'materials',
    'equipment',
    'transport',
    'marketing',
    'software',
    'other',
    'sales',
    'consulting',
  ]),
  description: z.string().optional(),
  date: z.string(),
});

export const zFinancialReportResponseDto = z.object({
  userId: z.string(),
  period: z.object({
    type: z.enum(['monthly', 'quarterly', 'annual']),
    startDate: z.iso
      .date()
      .regex(
        /^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$/,
      ),
    endDate: z.iso
      .date()
      .regex(
        /^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$/,
      ),
  }),
  generatedAt: z.string(),
  revenue: z.object({
    grossRevenue: z.number(),
    netRevenue: z.number(),
    vatCollected: z.number(),
  }),
  expenses: z.object({
    grossExpenses: z.number(),
    netExpenses: z.number(),
    vatDeductible: z.number(),
    payrollExpenses: z.object({
      grossSalaries: z.number(),
      netSalaries: z.number(),
      pensionFund: z.number(),
      medicalFund: z.number(),
      socialInsuranceFund: z.number(),
      totalPayrollTaxes: z.number(),
      totalPayrollCost: z.number(),
    }),
    socialContributionExpenses: z.object({
      pensionFund: z.number(),
      medicalFund: z.number(),
      socialInsuranceFund: z.number(),
      otherContributions: z.number(),
      totalSocialContributions: z.number(),
    }),
    administrativeExpenses: z.object({
      rent: z.number(),
      utilities: z.number(),
      leasing: z.number(),
      office: z.number(),
      services: z.number(),
      maintenance: z.number(),
      totalAdministrativeExpenses: z.number(),
    }),
    taxExpenses: z.object({
      vatToPay: z.number(),
      corporateIncomeTax: z.number(),
      otherTaxes: z.number(),
      totalTaxExpense: z.number(),
    }),
    operationalExpenses: z.object({
      materials: z.number(),
      equipment: z.number(),
      transport: z.number(),
      marketing: z.number(),
      software: z.number(),
      totalOperationalExpenses: z.number(),
    }),
    otherExpenses: z.object({
      uncategorized: z.number(),
      totalOtherExpenses: z.number(),
    }),
  }),
  vat: z.object({
    vatCollectedFromRevenue: z.number(),
    vatDeductibleFromExpenses: z.number(),
    vatToPay: z.number(),
  }),
  corporateResult: z.object({
    netRevenue: z.number(),
    netExpenses: z.number(),
    payrollCost: z.number(),
    operatingProfit: z.number(),
  }),
  finalResult: z.object({
    profitBeforeTax: z.number(),
    incomeTax: z.number(),
    profitAfterTax: z.number(),
  }),
});

export const zPaginatedTransactionsResponseDto = z.object({
  items: z.array(
    z.object({
      id: z.string().min(1),
      userId: z.string().min(1),
      type: z.enum(['income', 'expense']),
      amount: z.number().gt(0),
      category: z.enum([
        'salary',
        'rent',
        'utilities',
        'leasing',
        'office',
        'services',
        'maintenance',
        'materials',
        'equipment',
        'transport',
        'marketing',
        'software',
        'other',
        'sales',
        'consulting',
      ]),
      description: z.string().optional(),
      date: z.string(),
    }),
  ),
  page: z.int().gt(0).lte(9007199254740991),
  limit: z.int().gt(0).lte(9007199254740991),
  totalItems: z.int().gte(0).lte(9007199254740991),
  totalPages: z.int().gte(0).lte(9007199254740991),
});

export const zDeleteTransactionsDto = z.object({
  transactionIds: z.array(z.string().regex(/^[a-f\d]{24}$/)).min(1),
});

export const zDeleteTransactionsResponseDto = z.object({
  deletedCount: z.int().gte(0).lte(9007199254740991),
});

/**
 * Registration data required to create a new account.
 */
export const zAuthControllerRegisterBody = zRegisterDto;

/**
 * User registered successfully.
 */
export const zAuthControllerRegisterResponse = zAuthResponseDto;

/**
 * Login credentials.
 */
export const zAuthControllerLoginBody = zLoginDto;

/**
 * User authenticated successfully.
 */
export const zAuthControllerLoginResponse = zAuthResponseDto;

/**
 * Refresh token payload used to identify the session.
 */
export const zAuthControllerLogoutBody = zRefreshTokenDto;

/**
 * User logged out successfully.
 */
export const zAuthControllerLogoutResponse = zLogoutResponseDto;

/**
 * Refresh token payload.
 */
export const zAuthControllerRefreshTokenBody = zRefreshTokenDto;

/**
 * Token pair refreshed successfully.
 */
export const zAuthControllerRefreshTokenResponse = zAuthResponseDto;

/**
 * Token validation payload.
 */
export const zAuthControllerValidateTokenBody = zValidateTokenDto;

/**
 * Token is valid.
 */
export const zAuthControllerValidateTokenResponse = zValidateTokenResponseDto;

/**
 * Ids selected by the user for deletion.
 */
export const zFinancialControllerDeleteTransactionsBody =
  zDeleteTransactionsDto;

/**
 * Transactions deleted successfully.
 */
export const zFinancialControllerDeleteTransactionsResponse =
  zDeleteTransactionsResponseDto;

export const zFinancialControllerGetTransactionsQuery = z.object({
  page: z.int().gt(0).lte(9007199254740991).optional().default(1),
  limit: z.int().gt(0).lte(100).optional().default(20),
});

/**
 * Transactions loaded successfully.
 */
export const zFinancialControllerGetTransactionsResponse =
  zPaginatedTransactionsResponseDto;

/**
 * Transaction data to be saved in the financial service.
 */
export const zFinancialControllerCreateTransactionBody = zCreateTransactionDto;

/**
 * Transaction created successfully.
 */
export const zFinancialControllerCreateTransactionResponse =
  zTransactionResponseDto;

export const zFinancialControllerGetFinancialReportQuery = z.object({
  period: z.enum(['monthly', 'quarterly', 'annual']),
  startDate: z.iso
    .date()
    .regex(
      /^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$/,
    ),
  endDate: z.iso
    .date()
    .regex(
      /^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$/,
    ),
});

/**
 * Financial report generated successfully.
 */
export const zFinancialControllerGetFinancialReportResponse =
  zFinancialReportResponseDto;

export const zFinancialControllerGetFinancialReportPdfQuery = z.object({
  period: z.enum(['monthly', 'quarterly', 'annual']),
  startDate: z.iso
    .date()
    .regex(
      /^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$/,
    ),
  endDate: z.iso
    .date()
    .regex(
      /^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$/,
    ),
});

/**
 * PDF report generated successfully.
 */
export const zFinancialControllerGetFinancialReportPdfResponse = z.string();
