import { Injectable } from '@nestjs/common';
import {
  GenerateFinancialReportPdfRequest,
  GenerateFinancialReportPdfResponse,
} from '@financial-tracker/contracts';
import PDFDocument = require('pdfkit');

@Injectable()
export class PdfService {
  private createPdfBuffer(
    payload: GenerateFinancialReportPdfRequest,
  ): Promise<Buffer> {
    return new Promise((resolve) => {
      const doc = new PDFDocument({ margin: 50 });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));

      const report = payload.report;

      const money = (value: number): string => value.toFixed(2);

      const writeSectionTitle = (title: string): void => {
        doc.y += 18;
        doc.fontSize(18).fillColor('#1f2937').text(title, 50, doc.y, {
          width: 510,
          underline: true,
          align: 'left',
        });

        doc.y += 24;
        doc.x = 50;
      };

      const writeRow = (label: string, value: string | number): void => {
        const y = doc.y;

        doc.fontSize(14).fillColor('#374151').text(label, 50, y, {
          width: 280,
          lineBreak: false,
        });

        doc.fontSize(14).fillColor('#111827').text(String(value), 360, y, {
          width: 150,
          align: 'right',
          lineBreak: false,
        });

        doc.x = 50;
        doc.y = y + 18;
      };

      doc.fontSize(26).fillColor('#111827').text('Financial Report', {
        align: 'center',
      });

      doc.moveDown(0.5);
      doc
        .fontSize(14)
        .fillColor('#6b7280')
        .text(`User ID: ${report.userId}`, { align: 'center' })
        .text(`Period: ${report.period.startDate} - ${report.period.endDate}`, {
          align: 'center',
        })
        .text(`Generated at: ${report.generatedAt}`, { align: 'center' });

      doc.moveDown(1);
      doc.moveTo(50, doc.y).lineTo(560, doc.y).strokeColor('#d1d5db').stroke();

      writeSectionTitle('Revenue');
      writeRow('Gross revenue', money(report.revenue.grossRevenue));
      writeRow('Net revenue', money(report.revenue.netRevenue));
      writeRow('VAT collected', money(report.revenue.vatCollected));

      writeSectionTitle('Expenses');
      writeRow('Gross expenses', money(report.expenses.grossExpenses));
      writeRow('Net expenses', money(report.expenses.netExpenses));
      writeRow('VAT deductible', money(report.expenses.vatDeductible));
      writeRow(
        'Payroll cost',
        money(report.expenses.payrollExpenses.totalPayrollCost),
      );
      writeRow(
        'Administrative expenses',
        money(
          report.expenses.administrativeExpenses.totalAdministrativeExpenses,
        ),
      );
      writeRow(
        'Operational expenses',
        money(report.expenses.operationalExpenses.totalOperationalExpenses),
      );

      writeSectionTitle('VAT');
      writeRow(
        'VAT collected from revenue',
        money(report.vat.vatCollectedFromRevenue),
      );
      writeRow(
        'VAT deductible from expenses',
        money(report.vat.vatDeductibleFromExpenses),
      );
      writeRow('VAT to pay', money(report.vat.vatToPay));

      writeSectionTitle('Final Result');
      writeRow('Profit before tax', money(report.finalResult.profitBeforeTax));
      writeRow('Income tax', money(report.finalResult.incomeTax));
      writeRow('Profit after tax', money(report.finalResult.profitAfterTax));

      doc
        .fontSize(11)
        .fillColor('#6b7280')
        .text('Generated by Financial Tracker', 50, doc.page.height - 70, {
          width: doc.page.width - 100,
          align: 'center',
        });

      doc.end();
    });
  }

  async generateFinancialReport(
    payload: GenerateFinancialReportPdfRequest,
  ): Promise<GenerateFinancialReportPdfResponse> {
    const buffer = await this.createPdfBuffer(payload);

    return {
      fileName: `financial-report-${payload.userId}.pdf`,
      mimeType: 'application/pdf',
      contentBase64: buffer.toString('base64'),
    };
  }
}
